<?php

namespace Dende\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;
use Dende\MembersBundle\Entity\Member;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository {
    /**
     * Get all Members query
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getQuery() {
        $query = $this->createQueryBuilder("m");
        return $query;
    }

    public function getTotalCount() {
        $query = $this->getQuery();
        $query->select("count(m.id)");
        return $query->getQuery()->getSingleScalarResult();
    }

    public function getPaginator(QueryBuilder $query) {
        return new Paginator($query);
    }
    /**
     * @param QueryBuilder $query
     */
    public function setActiveCriteria(QueryBuilder $query) {
        $query->andWhere("m.deletedAt is null");
    }

    public function findOldVouchers() {
        $query = $this->getQuery();

        $query
                ->leftJoin("m.currentVoucher", "v")
                ->where("v.endDate < :date")
                ->setParameter("date", new \DateTime("now"))

        ;

        return $query->getQuery()->execute();
    }

}
