<?php

namespace Dende\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository {

    public function getActivitiesQuery() {
        return $this->createQueryBuilder("a")
                        ->select();
    }

    public function getAllActivities() {
        return $this->getActivitiesQuery()->getQuery()->execute();
    }

    public function getTodayActivities($today = null) { {
            if (!$today)
            {
                $today = strtolower(date('l'));
            }

            return $this->getActivitiesQuery()
                            ->join("a.events", "e")
                            ->where("e.dayOfWeek = :day")
                            ->setParameter("day", $today)
                            ->getQuery()->execute();
        }
    }

}
