<?php

namespace Dende\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository {

    public function getActivitiesQuery() {
        return $this->createQueryBuilder("a")
                        ->select();
    }

    public function getAllActivities() {
        return $this->getActivitiesQuery()->getQuery()->execute();
    }

}
