parameters:
    base_manager.class: Dende\EntriesBundle\Services\Manager\BaseManager
    entry_entity.class: Dende\EntriesBundle\Entity\Entry
    entry_manager.class: Dende\EntriesBundle\Services\Manager\EntryManager
    entry_repository.class: Dende\EntriesBundle\Entity\EntryRepository

services:
#    base_manager:
#        class:     "%base_manager.class%"
#        calls:
#             - [ setContainer, ["@service_container"] ]
    entry_repository:
        class:          "%entry_repository.class%"
        factory_service: doctrine
        factory_method:  getRepository
        arguments: [ "%entry_entity.class%" ]
        
    entry_manager:
        class:          "%entry_manager.class%"
        parent:         base_manager
        calls:
             - [ setClass, [%entry_entity.class%] ]
             - [ setRepository, ["@entry_repository"] ]

    dende.update_left_amount_listener:
        class: Dende\EntriesBundle\Services\Listener\UpdateLeftAmountListener
        # TODO: very bad, temporarily workaround of circular
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            
#    validator.left_amount_validator:
#        class: Dende\EntriesBundle\Validator\LeftAmountValidator
#        tags:
#            - { name: validator.constraint_validator, alias: left_amount_constraint }