<?php

namespace Dende\EntriesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dende\ListsBundle\Entity\RepositoryListCompatible;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository implements RepositoryListCompatible {

    public function getAllEntries() {
        return $this->createQueryBuilder("e")
                        ->getQuery()->execute();
    }

    /**
     * 
     * @return QueryBuilder
     */
    public function getQuery() {
        return $this->createQueryBuilder("e");
    }

    public function getTotalCount() {
        $query = $this->getQuery();
        $query->select("count(e.id)");
        return $query->getQuery()->getSingleScalarResult();
    }

    public function getPaginator(QueryBuilder $query) {
        return new Paginator($query);
    }

}
