<?php

namespace Dende\EntriesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository {

    public function getAllEntries() {
        return $this->createQueryBuilder("e")
                        ->getQuery()->execute();
    }

}
